_meta_: {}
bundle_root: /work_dir/dints_0
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)
data_file_base_dir: /Data
data_list_file_path: /work_dir/auto3dseg.json
finetune: {activate: false, pretrained_ckpt_name: $@bundle_root + '/model_fold' +
    str(@fold) + '/best_metric_model.pt'}
fold: 0
infer: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  data_list_key: testing, fast: false, output_path: $@bundle_root + '/prediction_'
    + @infer#data_list_key}
show_cache_progress: false
training:
  adapt_valid_mode: true
  adapt_valid_num_epochs_per_validation: [2, 4, 2]
  adapt_valid_progress_percentages: [10, 40, 70]
  amp: true
  cache_rate: 0
  early_stop_delta: 0
  early_stop_mode: true
  early_stop_patience: 20
  input_channels: 1
  learning_rate: 0.2
  log_output_file: $@bundle_root + '/model_fold' + str(@fold) + '/training.log'
  loss: {_target_: DiceFocalLoss, batch: true, include_background: true, sigmoid: $not
      @training#softmax, smooth_dr: 1.0e-05, smooth_nr: 1.0e-05, softmax: $@training#softmax,
    squared_pred: true, to_onehot_y: $@training#softmax}
  lr_scheduler: {_target_: torch.optim.lr_scheduler.PolynomialLR, optimizer: $@training#optimizer,
    power: 0.5, total_iters: $@training#num_epochs // @training#num_epochs_per_validation
      + 1}
  num_cache_workers: 8
  num_epochs: 300
  num_epochs_per_validation: 2
  num_images_per_batch: 6
  num_patches_per_image: 14
  num_patches_per_iter: 14
  num_sw_batch_size: $@training#num_patches_per_iter
  num_workers: 6
  num_workers_validation: 16
  optimizer: {_target_: torch.optim.SGD, lr: '@training#learning_rate', momentum: 0.9,
    weight_decay: 4.0e-05}
  output_classes: 12
  overlap_ratio: 0.625
  patch_size: [96, 96, 32]
  patch_size_valid: [96, 96, 32]
  random_seed: 0
  resample_to_spacing: [1.0, 1.0, 1.0]
  softmax: true
  sw_input_on_cpu: false
  train_cache_rate: $@training#cache_rate
  transforms: {lazy_resampling: true, resample_to_spacing: $@training#resample_to_spacing}
  validate_cache_rate: $@training#cache_rate
validate: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  output_path: $@bundle_root + '/prediction_fold' + str(@fold), save_mask: true}
