_meta_: {}
adapt_valid_mode: true
adapt_valid_num_epochs_per_validation: [2, 4, 2]
adapt_valid_progress_percentages: [10, 40, 70]
amp: true
bundle_root: /work_dir/swinunetr_0
cache_rate: 0
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)
data_file_base_dir: /Data
data_list_file_path: /work_dir/auto3dseg.json
early_stop_delta: 0
early_stop_mode: true
early_stop_patience: 20
finetune: {activate: false, pretrained_ckpt_name: $@bundle_root + '/model_fold' +
    str(@fold) + '/best_metric_model.pt'}
fold: 0
infer: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  data_list_key: testing, fast: false, output_path: $@bundle_root + '/prediction_'
    + @infer#data_list_key}
input_channels: 1
learning_rate: 0.0004
log_output_file: $@bundle_root + '/model_fold' + str(@fold) + '/training.log'
loss: {_target_: DiceCELoss, include_background: true, sigmoid: $not @softmax, smooth_dr: 1.0e-05,
  smooth_nr: 0, softmax: $@softmax, squared_pred: true, to_onehot_y: $@softmax}
lr_scheduler: {_target_: monai.optimizers.WarmupCosineSchedule, optimizer: $@optimizer,
  t_total: $@num_epochs // @num_epochs_per_validation + 1, warmup_steps: $@num_epochs//100}
num_cache_workers: 8
num_epochs: 200
num_epochs_per_validation: 2
num_images_per_batch: 4
num_patches_per_image: 6
num_patches_per_iter: 6
num_sw_batch_size: $@num_patches_per_iter
num_workers: 8
num_workers_validation: 4
optimizer: {_target_: torch.optim.AdamW, lr: '@learning_rate', weight_decay: 1.0e-05}
output_classes: 12
overlap_ratio: 0.5
patch_size: [96, 96, 64]
patch_size_valid: [96, 96, 64]
pretrained_path: $@bundle_root + '/pretrained_model' + '/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt'
random_seed: 0
resample_to_spacing: [1.0, 1.0, 1.0]
show_cache_progress: false
softmax: true
sw_input_on_cpu: false
train_cache_rate: $@cache_rate
transforms: {lazy_resampling: false, resample_to_spacing: $@resample_to_spacing}
use_pretrain: true
validate: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  output_path: $@bundle_root + '/prediction_fold' + str(@fold), save_mask: true}
validate_cache_rate: $@cache_rate
