_meta_: {}
image_key: image
transforms_infer:
  _target_: Compose
  transforms:
  - {_target_: LoadImaged, keys: '@image_key'}
  - {_target_: EnsureChannelFirstd, keys: '@image_key'}
  - {_target_: Orientationd, axcodes: RAS, keys: '@image_key'}
  - {_target_: Spacingd, align_corners: true, keys: '@image_key', mode: bilinear,
    pixdim: $@resample_to_spacing}
  - {_target_: CastToTyped, dtype: $torch.float32, keys: '@image_key'}
  - {_target_: NormalizeIntensityd, channel_wise: true, keys: '@image_key', nonzero: true}
  - {_target_: CastToTyped, dtype: $torch.float32, keys: '@image_key'}
